---
layout: 'src/layouts/ru/Post.astro'
title: 'Exceptions in v8'
pubDate: 'Nov 11 2020'
tags: ['javascript']
description: 'В статье Михаел рассматривает две небольшие функции, где первая бросает исключения, а вторая ловит. Далее приводит байт код этих двух функций полученный с помощью флага --print-bytecode...'
---

В статье Михаел рассматривает две небольшие функции, где первая бросает исключения, а вторая ловит. Далее приводит байт код этих двух функций полученный с помощью флага --print-bytecode.

Чтобы понять, что делает команда Throw в байт-коде, автор обращается к файлу движка v8 interpreter-generator.cc откуда в последствии доходит до функции Isolate::Throw. Эта функция сохраняет объект исключения как изолированный объект
и возвращает контрольное значение в корневое глобальное множество. После исключение находится в состоянии pending ..

Что происходит далее читайте по ссылке ниже

https://ripsawridge.github.io/articles/exceptions/
